### ISSUE TITLE
How do I run this on linux?

### ISSUE THREAD

**Issue by lihop** [mrkno/AgilefantTimes#1]
Props to you fellows for creating this. This is awesome!
BTW: I'm running NixOS version: 15.05.git.1934ef6 (Dingo) (which is subject to change at any commit).

**Comment by 4-Eyes** [comment]
You'll need to download (if you haven't already) and use mono to compile it. Here's the website for it, http://www.mono-project.com. All the documentation you need for how to compile  should be there. But if you get stuck I'm sure we can help you out.

**Comment by ghost** [comment]
I'm pretty sure it's already on most of the Lab machines. You should be able to run it with "mono Thingy.exe" (I don't remember what the name of the .exe is sorry)

**Comment by drkno** [comment]
@thesquareof4 @lihop its "mono AgilefantTimes.exe", although I'm not sure what the min version of mono is for it to be supported. I had slight problems with getting it to run on the outdated version of mono on the lab machines.

**Comment by ghost** [comment]
One last thing, download the pre compiled dev release, as compiling could be a pain

**Comment by drkno** [comment]
Now compatible with mono 3.12.1 as of commit 520c21d7e49dea919e9da5cbf7a2a61d9b9293a9
