### ISSUE TITLE
Data Contracts are messy

### ISSUE THREAD

**Issue by ghost** [mrkno/AgilefantTimes#3]
Maybe we should swap to NewtonSoft.Json?

**Comment by drkno** [comment]
Primary reason for going to DataContract's was to avoid adding 3rd party libraries that could potentially cause issues with mono. Also although they are messy they are pretty easy to use.

**Comment by drkno** [comment]
Thinking about it, if we add much more functionality to this project rather than splitting it into a separate one then we probably should move to a nicer library for ease of use. Otherwise we should just leave it as is. What do you think? @4-Eyes @thesquareof4 @Awarua-
