### ISSUE TITLE
Link to v0.5 RedHatInstall.sh script broken

### ISSUE THREAD

**Issue by lihop** [mrkno/AgilefantTimes#5]
The following link in the README for installing on the University of Canterbury jenkins servers fails with a 404 error:

```
wget https://github.com/mrkno/AgilefantTimes/releases/download/v0.5/RedHatInstall.sh
```

There is no RedHatInstall.sh file in the downloads section of the [0.5 release](https://github.com/mrkno/AgilefantTimes/releases/tag/v0.5).

**Comment by ghost** [comment]
There is now
